Repository go-vela/compiler, pull requests merged in 2019-12, with the labels that each got.

#20 Inject init stage/step to pipeline
  compiler/compiler.go
  compiler/native/clone.go
  compiler/native/compile.go
  compiler/native/compile_test.go
  compiler/native/initialize.go
  compiler/native/initialize_test.go
Labels: feature

#21 Release v0.2.0-rc2
  go.mod
  go.sum
Labels: enhancement

#22 Update all go mod dependencies
  go.mod
  go.sum
Labels: enhancement

#24 Add Metadata for compiler
  compiler/compiler.go
  compiler/metadata.go
  compiler/native/compile_test.go
  compiler/native/environment.go
  compiler/native/environment_test.go
  compiler/native/native.go
  compiler/native/native_test.go
  compiler/native/script_test.go
Labels: feature

#25 Move Metadata to go-vela/types
  compiler/compiler.go
  compiler/metadata.go
  compiler/native/environment.go
  compiler/native/environment_test.go
  compiler/native/native.go
  compiler/native/native_test.go
  go.mod
  go.sum
Labels: enhancement

#26 Add Actions pipeline for changelog
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: feature

#27 feat(build): add email and link fields
  compiler/native/environment.go
  compiler/native/environment_test.go
  go.mod
  go.sum
Labels: feature

#28 chore: update go-vela dependencies
  go.mod
  go.sum
Labels: enhancement

#29 ci: switch from coveralls to codecov
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#30 ci: add explicit configuration for automation
  .golangci.yml
  codecov.yml
Labels: enhancement

#31 refactor: fix linter errors
  compiler/native/compile_test.go
  compiler/native/expand.go
  compiler/native/expand_test.go
  compiler/native/native.go
  compiler/native/parse.go
  compiler/native/parse_test.go
  compiler/native/unmarshal.go
  registry/github/github.go
  registry/github/github_test.go
Labels: enhancement

#32 chore: update for v0.2.0
  go.mod
  go.sum
Labels: dependencies

#33 ci(linters): update funlen linter settings
  .golangci.yml
Labels: enhancement
