Repository go-vela/compiler, pull requests merged in 2019-11, with the labels that each got.

#4 Update path to clone plugin
  compiler/native/clone.go
  compiler/native/clone_test.go
  compiler/native/compile_test.go
Labels: bug

#6 Use goveralls to report test coverage to coveralls
  .github/workflows/test.yml
Labels: enhancement

#7 Add badges to readme
  .github/README.md
Labels: enhancement

#8 Upgrade Vela dependencies for login bug
  go.mod
  go.sum
Labels: bug

#10 Refactor to improve Go Report Card
  compiler/native/clone.go
  compiler/native/compile.go
  compiler/native/environment.go
  compiler/native/expand.go
  compiler/native/expand_test.go
  compiler/native/native.go
  compiler/native/native_test.go
  compiler/native/parse.go
  compiler/native/script.go
  compiler/native/transform.go
  compiler/native/validate.go
Labels: enhancement

#11 Update go dependencies for types
  go.mod
  go.sum
Labels: enhancement

#12 Resolve not hardcoding source system environment variables
  compiler/native/environment.go
  compiler/native/environment_test.go
Labels: bug

#13 Adopt official mattn/goveralls integration
  .github/workflows/test.yml
Labels: enhancement

#14 Update go-vela/types for Repo field rename
  go.mod
  go.sum
Labels: bug

#15 Resolve Yaml anchors and container ID bugs
  compiler/native/parse.go
  compiler/native/transform.go
  compiler/native/transform_test.go
  go.mod
  go.sum
Labels: bug

#16 Update go-vela/types for bug fixes
  go.mod
  go.sum
Labels: bug

#17 Add disclaimer
  .github/README.md
Labels: enhancement

#18 Add the worker struct for routing to workers
  compiler/native/transform.go
  compiler/native/transform_test.go
  go.mod
  go.sum
Labels: feature
