Repository go-vela/compiler, pull requests merged in 2020-05, with the labels that each got.

#61 chore: update dependencies to v0.4.0
  go.mod
  go.sum
Labels: dependencies

#64 fix: enable running step with env or secrets
  compiler/native/validate.go
Labels: bug

#65 chore: update dependencies for release
  compiler/native/transform_test.go
  go.mod
  go.sum
Labels: dependencies

#66 chore: update for patch release v0.4.2
  go.mod
  go.sum
Labels: dependencies

#67 chore: update for patch release v0.4.3
  go.mod
  go.sum
Labels: dependencies

#68 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement
