Repository go-vela/compiler, pull requests merged in 2020-04, with the labels that each got.

#45 feat(compiler): add substitute func
  .github/README.md
  LICENSE
  compiler/engine.go
  compiler/native/compile.go
  compiler/native/substitute.go
  compiler/native/substitute_test.go
  go.mod
  go.sum
Labels: bug, feature

#48 fix(environment): populating BUILD_TAG variable
  compiler/native/environment.go
Labels: bug

#46 feat: add comment support to client
  compiler/engine.go
  compiler/native/compile.go
  compiler/native/compile_test.go
  compiler/native/native.go
  compiler/native/native_test.go
  compiler/native/transform_test.go
  go.mod
  go.sum
Labels: feature

#51 chore: update for v0.4.0-rc1
  go.mod
  go.sum
Labels: dependencies

#58 fix(substitute): skip unfound env vars
  compiler/native/substitute.go
  compiler/native/substitute_test.go
  go.mod
Labels: bug

#59 chore: update version to v0.4.0-rc3
  go.mod
  go.sum
Labels: dependencies

#60 feat(deployment): add build target
  compiler/native/compile.go
  compiler/native/environment.go
  compiler/native/environment_test.go
  go.mod
  go.sum
Labels: feature
