Repository go-vela/compiler, pull requests merged in 2021-02, with the labels that each got.

#129 chore: linter setup and fixes, doc changes
  .github/CONTRIBUTING.md
  .golangci.yml
  compiler/native/compile.go
  compiler/native/expand.go
  compiler/native/native.go
  compiler/native/parse_test.go
  compiler/native/script.go
  registry/github/github.go
  registry/github/template.go
  template/starlark/convert_test.go
  template/starlark/render.go
  template/starlark/starlark.go
Labels: enhancement

#130 chore: upgrade go-vela/types on v0.7.0
  go.mod
  go.sum
Labels: dependencies

#133 revert: library swap to goccy
  compiler/engine.go
  compiler/native/compile.go
  compiler/native/parse.go
  compiler/native/parse_test.go
  compiler/native/substitute.go
  compiler/native/testdata/invalid.yml
  compiler/native/validate.go
  compiler/native/validate_test.go
  go.mod
  go.sum
  template/native/render.go
  template/native/render_test.go
  template/native/testdata/invalid.yml
  template/starlark/render.go
  template/starlark/render_test.go
Labels: bug

#138 fix: missing validate on interface from revert
  compiler/engine.go
Labels: bug

#140 fix(local): skip OS environment for detached processes
  compiler/native/environment.go
Labels: bug

#143 fix: properly handle default branch
  compiler/native/expand.go
  registry/github/parse.go
  registry/github/parse_test.go
  registry/github/template.go
  registry/github/template_test.go
  registry/registry.go
Labels: bug
