Repository go-vela/compiler, pull requests merged in 2021-01, with the labels that each got.

#104 refactor: set step directory from environment
  compiler/native/transform.go
  compiler/native/transform_test.go
Labels: enhancement

#105 chore: add nolint comment for gosec
  compiler/native/transform.go
Labels: enhancement

#91 refactor: swap yaml libraries
  compiler/engine.go
  compiler/native/compile.go
  compiler/native/compile_test.go
  compiler/native/parse.go
  compiler/native/parse_test.go
  compiler/native/substitute.go
  compiler/native/testdata/invalid.yml
  compiler/native/transform_test.go
  compiler/native/validate.go
  compiler/native/validate_test.go
  go.mod
  go.sum
  template/native/render.go
  template/native/render_test.go
  template/native/testdata/invalid.yml
  template/starlark/render.go
  template/starlark/render_test.go
Labels: dependencies, enhancement

#107 chore(deps): revert k8s.io/apimachinery to v0.17.3 v2
  go.mod
  go.sum
Labels: dependencies

#109 feat(clone): allow user to disable clone within step and stage
  compiler/native/compile.go
  compiler/native/compile_test.go
  compiler/native/testdata/clone_false.yml
  compiler/native/testdata/clone_replace.yml
  compiler/native/testdata/clone_true.yml
Labels: feature

#110 feat: skip clone process for local pipelines
  compiler/engine.go
  compiler/native/clone.go
  compiler/native/clone_test.go
  compiler/native/native.go
  compiler/native/native_test.go
  compiler/native/transform.go
  compiler/native/transform_test.go
Labels: feature

#114 refactor: update fallback workspace from /vela to /vela/src
  compiler/native/environment.go
  compiler/native/environment_test.go
  compiler/native/transform_test.go
  go.mod
  go.sum
Labels: enhancement

#115 chore(deps): upgrade go-vela/types on v0.7.0-rc2
  go.mod
  go.sum
Labels: dependencies

#117 chore: update copyright year to 2021
  .github/README.md
  LICENSE
  Makefile
  compiler/context.go
  compiler/doc.go
  compiler/engine.go
  compiler/native/clone.go
  compiler/native/clone_test.go
  compiler/native/compile.go
  compiler/native/compile_test.go
  compiler/native/doc.go
  compiler/native/environment.go
  compiler/native/environment_test.go
  compiler/native/expand.go
  compiler/native/expand_test.go
  compiler/native/initialize.go
  compiler/native/initialize_test.go
  compiler/native/native.go
  compiler/native/native_test.go
  compiler/native/parse.go
  compiler/native/parse_test.go
  compiler/native/script.go
  compiler/native/script_test.go
  compiler/native/substitute.go
  compiler/native/substitute_test.go
  compiler/native/transform.go
  compiler/native/transform_test.go
  registry/doc.go
  registry/github/doc.go
  registry/github/github.go
  registry/github/github_test.go
  registry/github/parse.go
  registry/github/parse_test.go
  registry/github/template.go
  registry/github/template_test.go
  registry/registry.go
  registry/source.go
  template/doc.go
  template/native/doc.go
  template/native/render_test.go
  template/starlark/convert.go
  template/starlark/convert_test.go
  template/starlark/render.go
  template/starlark/render_test.go
  template/starlark/starlark.go
  template/template.go
Labels: enhancement

#121 refactor: allow overrides of local variables
  compiler/native/transform.go
Labels: enhancement

#124 feat: set os env vars for local compiler
  compiler/native/environment.go
Labels: feature
