Repository go-vela/compiler, pull requests merged in 2021-05, with the labels that each got.

#179 enhance(templates): enable secret references
  compiler/engine.go
  compiler/native/compile.go
  compiler/native/compile_test.go
  compiler/native/expand.go
  compiler/native/expand_test.go
  compiler/native/testdata/template.json
  template/native/render.go
  template/native/render_test.go
  template/starlark/render.go
  template/starlark/render_test.go
Labels: enhancement

#182 chore: upgrade go-vela/types on v0.8.0-rc1
  compiler/native/environment_test.go
  go.mod
  go.sum
Labels: dependencies

#184 fix(secrets/services): populate environment within stages before plan
  compiler/native/compile.go
  compiler/native/compile_test.go
Labels: bug

#185 chore: upgrade go-vela/types on v0.8.0-rc2
  go.mod
  go.sum
Labels: dependencies
