Repository go-vela/compiler, pull requests merged in 2021-08, with the labels that each got.

#211 chore: add required compiler components for template validation
  compiler/engine.go
  compiler/native/expand.go
  compiler/native/native.go
  compiler/native/native_test.go
  go.mod
  go.sum
Labels: enhancement

#209 bug(template): more informative error when invalid template defined in pipeline
  registry/github/parse.go
Labels: bug

#215 chore: remove sdk-go as dependency
  compiler/native/compile_test.go
  go.mod
  go.sum
Labels: dependencies

#216 chore: upgrade dependencies for v0.9.0-rc1
  go.mod
  go.sum
Labels: dependencies

#218 chore: upgrade dependencies for v0.9.0-rc2
  go.mod
  go.sum
Labels: dependencies
